{% set name = "cymem" %}
{% set version = "2.0.3" %}
{% set sha256sum = "5083b2ab5fe13ced094a82e0df465e2dbbd9b1c013288888035e24fd6eb4ed01" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - patches/0001-remove-setup_requires.patch
    - patches/0002-always-cythonize.patch

build:
  number: 3
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  skip: True  # [win32 or linux32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python

test:
  requires:
    - pytest

about:
  home: https://github.com/explosion/cymem
  license: MIT
  license_file: LICENSE
  summary: Manage calls to calloc/free through Cython
  description: |
    cymem provides two small memory-management helpers for Cython. They make it
    easy to tie memory to a Python object’s life-cycle, so that the memory is
    freed when the object is garbage collected.

extra:
  recipe-maintainers:
    - rmax
    - h-vetinari
    - ines
    - honnibal
    - adrianeboyd
