{% set version = "2.0.5" %}
{% set sha256sum = "bf4c9adc15535c6250aee24d3465e088b344e1c3304a6641f20f07081c9f0ac5" %}

package:
  name: cymem
  version: {{ version }}

source:
  # We don't use the PyPI release because it does not include the cythonize.py
  # helper script to rebuild from the Cython source.
  # url: https://pypi.io/packages/source/c/cymem/cymem-{{ version }}.tar.gz
  url: https://github.com/explosion/cymem/archive/v{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - patches/0001-remove-setup_requires.patch
    - patches/0002-always-cythonize.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - cymem
  commands:
    - python -m pytest --tb=native --pyargs cymem

about:
  home: https://github.com/explosion/cymem
  license: MIT
  license_file: LICENSE
  summary: Manage calls to calloc/free through Cython
  description: |
    cymem provides two small memory-management helpers for Cython. They make it
    easy to tie memory to a Python object’s life-cycle, so that the memory is
    freed when the object is garbage collected.

extra:
  recipe-maintainers:
    - rmax
    - h-vetinari
    - ines
    - honnibal
    - adrianeboyd
